- name: Create {{ systemd_service_name }} systemd service
  template:
    src: service.j2
    dest: /etc/systemd/system/{{ systemd_service_name }}.service
    owner: root
    group: root
    mode: 0644
  notify:
    -  Restart {{ systemd_service_name }} service